# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 17:41
from __future__ import unicode_literals

import audiotracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiotracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=audiotracks.models.get_audio_upload_path, verbose_name='Audio file'),
        ),
    ]
